language: go
go:
  - "1.12"
  - "1.13"

before_install:
  - go get github.com/golang/lint/golint

script:
  - make dep
  - make check
  - make test
  - make all

after_success:
  - bash <(curl -s https://codecov.io/bash)
